assets:
  overrides:
    /: ../frontend/

server:
  rootPath: '/api/*'

database:
  driverClass: org.sqlite.JDBC
  user: note
  password: notes!
  url: jdbc:sqlite:notes.db
  properties:
    charSet: UTF-8